CREATE TABLE IF NOT EXISTS CARTAO
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMEDOCLIENTE TEXT NOT NULL,
    NUMERODOCARTAO INTEGER NOT NULL,
    VENCIMENTO DATE NOT NULL,
    CPFDOCLIENTE TEXT NOT NULL
);