CREATE TABLE IF NOT EXISTS TRANSACOES
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NUMERODOCARTAO INTEGER NOT NULL,
    VENCIMENTO DATE NOT NULL,
    CPFDOCLIENTE TEXT NOT NULL,
    VALORDATRANSACAO FLOAT NOT NULL,
    DATATRANSACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    IDTRANSACAO INTEGER NOT NULL,
    LIMITECARTAO FLOAT NOT NULL
);